# Generated by Django 4.1.1 on 2022-10-18 21:31

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_whyus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='Event price')),
                ('description', models.TextField(max_length=1000)),
                ('subtitle1', models.TextField(blank=True, verbose_name='sub1')),
                ('subtitle2', models.TextField(blank=True, verbose_name='sub2')),
                ('subtitle3', models.TextField(blank=True, verbose_name='sub3')),
                ('aftertitle', models.TextField(blank=True, verbose_name='After text')),
                ('photo', models.ImageField(upload_to=main_page.models.Events.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
