# Generated by Django 4.1.1 on 2022-10-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreservations',
            name='email',
        ),
        migrations.AddField(
            model_name='userreservations',
            name='persons',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
